var GAME_LEVELS = [
  ["                                                                                ",
   "                                      xxx                                       ",
   "                             xxxxx    xvx                                       ",
   "                             xvvvx                                              ",
   "                                                        o          o            ",
   "                                                                                ",
   "                                                                  xxx           ",
   "            xxx                                    xx  = = xx    xx!xx          ",
   "       xxxxxx!xxxxxx                  o o      xx                x!!!x          ",
   "       x!!!!!!!!!!!x                                             xx!xx          ",
   "       x|x xx xxxx x                 xxxxx                        xvx           ",
   "  xx                                            o o o                        x  ",
   "  x          |          o                                                  o x  ",
   "  x       |             o      o               xxxxxxxx            o         x  ",
   "  x          o          o                                                  xxx  ",
   "  x  @            |                                              xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxx   xxxx   xx  ",
   "                             x!!!x                  x!!!!!x             x!!!x   ",
   "                             x!!!x                  x!!!!!x             x!!!x   ",
   "                             xxxxx                  xxxxxxx             xxxxx   ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x   ooo                                               !!xxxxxxxxxxx!!    ",
   "                                      x!!x                                                   !!xxxxxxxxxxxxxxx!!  ",
   "                                      x!!xxxxxxxxxxxxxxxx                                  !!xxxxxxxxxxxxxxxxxx!! ",
   "                                      xx!!!!!!!!!!xx    xx                                !!!|!!!! !!!|||!!! !!!!!",
   "                                      xvxxxxxxxxx!!x     xx       o                                             !!",
   "                                                 x!x      xx                                                |   !!",
   "                                                 x!x            xxxx                               |            !!",
   "                                                 xvx           xx                                               !!",
   "                                                          xxxxxx|                                   o  o        !!",
   " xxx             xxx                                     xx                        o             o        o     !!",
   " xvx           xxxvxxx           =                      xx                                                      !!",
   "               x!! !!x                         x     xxxxv                         x    xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                               x     x                             x         x                    ",
   "                                               x     x                           o x         x                    ",
   "                                          o    x     x                             xx        x                    ",
   "                                              xxx    x                   xxx     xxx         x                    ",
   "                                               x     x      o  o   xxx   x!!!!!!!!!x         x                    ",
   "                              xxx   xxxxxxxxxxxx     x               x   x!!!!!!!! x         x                    ",
   "             xxxx               x   x!!!!!!!!!!x     x=====xxxxxx====x   x!!!xxxxxxxxx       x                    ",
   "             x                  x o x!!!!!!!!!!x    xx!!!!!!!!!!!!!!!x   x!!!x               x                    ",
   "     @       x         xxx    o x   x!!!!!!!!!!x     x!!!!!!!!!!!!!!!x   x!!!x               x                    ",
   "  o xxx      xxx       x        x   x!!!!!!!!!!x     x!!!!!!!!!!!!!!!x   xxxxx   xxxxxx      x                    ",
   "    x x      x       xxx     xxxx o x!!!!!!!!!!x     x!!!!!!!!!!!!!!!x     o     x x         x                    ",
   "xxxxx x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!!!x           x x         x                    ",
   "x!!!x x!!!!!!xxxx      x!!!!!xx       xxxxxxxxxx     x!!!!!!!!!!!!!!!xxxxxxxxxxxxx xx  o o  xx                    ",
   "x!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx                      xx     xx                     ",
   "x!!!x x!!!!!!x      xxxx!!!!!x                  =  xx!!!!!!xx                        xxxxxxx                      ",
   "x!!!x x!!!!!!x  ooo    x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx                                                      ",
   "x!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                                       ",
   "xxxxx x!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                       !    !    !                            ",
   "                                                                      !     !   !                             ",
   "                                                                      !   !   !                               ",
   "                                                                       !   !   !                              ",
   "                                                                      !   !     !                             ",
   "                                                                     xxxxxxxxxxxxx                            ",
   "                                                                     xxxxxxxxxxxxx                            ",
   "                                                                     xxxxxxxxxxxxx                            ",
   "                                                                     xxxxxxxxxxxxx                            ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!v!! !!|!v!xxxxxxxxxxx                  ",
   "                  xx     xvx         xxxxxxxxxxxxxxxx                                        xx               ",
   "                xx                      |                                  |                    xx            ",
   "              xx                                                                                 xx           ",
   "            xx                                |             o                                      xx         ",
   "          xx                                                                                         xx       ",
   "        xx                                                                                             xx     ",
   "      xx                           xxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxx                     xx   ",
   "    xx     o                       x      |             x!!!!!!!x    x!!  !!  !! ! x     =                 x  ",
   "  xx                               x                    x!!!!!!!x    x           | x                       x  ",
   "  x        xx       xxxxxxxxxxxxxxxx                    x!!!!!!!x    x    |        x            =          x  ",
   "  x!!!!!!!!!xx                                          xxxxxxxxx    x             x                       x  ",
   "  x!!!!!!!!!!xx                                                                |   x                       x  ",
   "  x!!!!!!!!!!!xx                                                                   x                  o    x  ",
   "  xxxxxxxxxxxxxxxxxxxx                                                             x  o               o    x  ",
   "  x                  x                                                             x                       x  ",
   "  x                  x             x   xxxxxxxx    xxxxxxxx                        xxxxxxx         xxxxxxxxx  ",
   "  x                  xxxxxxxxxxxxxxx!!!x      x!!!!x      x                              x!!!!!!!!!x       x  ",
   "  x                                xxxxx      xxxxxx      xxxxxxxx                       x!!!!!!!!!x       x  ",
   "  x                       o                                                              x!!!!!!!!!x       x  ",
   "  x      @                                     =                                         x!!!!!!!!!x       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                yy       yy yyyyyyyyyy   yy    yy        yy           yy  yyyyyy  yy       yy               x",
   "x                 yy     yy  yy      yy   yy    yy        yy           yy    yy    yy yy    yy               x",
   "x                  yy   yy   yy      yy   yy    yy        yy     yy    yy    yy    yy  yy   yy               x",
   "x                   yy yy    yy      yy   yy    yy        yy   yy  yy  yy    yy    yy   yy  yy               x",
   "x   @               yy       yy      yy   yy    yy        yy yy     yy yy    yy    yy    yy yy               x",
   "x                  yy        yyyyyyyyyy   yyyyyyyy        yy           yy  yyyyyy  yy       yy               x",
   "x                                                                                                            x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
